#!/usr/bin/env python2

import sys
import math

if len(sys.argv) != 4:
	print 'wrong usage'
	sys.exit(1)

inp = open(sys.argv[1])
outp = open(sys.argv[3])

T, N = map(int, inp.readline().split())
A = map(int, inp.readline().split())

ans = A[1]-A[0]
for i in xrange(1, N):
	ans = max(ans, A[i]-A[i-1])

def wrong():
	print 0
	print >>sys.stderr, 'translate:wrong'

def correct():
	print 1
	print >>sys.stderr, 'translate:success'

def partial(score):
	print score
	print >>sys.stderr, 'translate:partial'

try:
	lines = outp.readlines()
	if len(lines) != 2:
		wrong()
	your_ans = int(lines[0])
	if ans != your_ans:
		wrong()
	M = int(lines[1])
	if T == 1:
		if M <= (N+1)/2:
			correct()
		else:
			wrong()
	elif T == 2:
		if M <= 3*N:
			correct()
		else:
			partial(60.0/((float(M)/N+1)**0.5-1) / 70.0)

except:
	wrong()
